
project_id = "bfscrjrjwbzpldamcrbz"

[functions.transcript-processing-health]
verify_jwt = false

[functions.fix-transcript-paths]
verify_jwt = false

[functions.trigger-transcript-processing]
verify_jwt = false

[functions.process-transcript]
verify_jwt = false
