
project_id = "bfscrjrjwbzpldamcrbz"

[functions.gemini-chat]
verify_jwt = false

[functions.gemini-chat.voice-conversation]
verify_jwt = false

[functions.analytics-insights]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.validate-service-account]
verify_jwt = false
