
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "LightRAG"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

[inbucket]
# Port to use for the email testing server UI.
port = 54324
# Uncomment to expose additional ports for testing from other applications.
# smtp_port = 54325
# pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true
# If disabled, the user will be able to change their email with just the email OTP.
# If enabled, email change requires both email and phone verification OTPs.
secure_email_change_enabled = true

[auth.sms]
twilio_sender = ""

[auth.hooks]
# invoke_signup_hook = true
# invoke_token_refresh_hook = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.email.template.invite]
subject = "You have been invited"
content_path = ""

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = ""

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = ""

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = ""

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = ""

[functions]
# Port to serve Edge Functions on.
port = 54321

[functions.search_embeddings]
# Enable/disable the function locally.
enabled = true
# Provides permissions for the function to access other services in your stack.
verify_jwt = true
