
project_id = "bfscrjrjwbzpldamcrbz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[edge_functions]
[edge_functions.fix-transcript-paths]
verify_jwt = true

[edge_functions.process-transcript]
verify_jwt = true

[edge_functions.transcript-webhook]
verify_jwt = true

[edge_functions.transcript-processing-health] 
verify_jwt = true

[edge_functions.trigger-transcript-processing]
verify_jwt = true

[edge_functions.process-with-hierarchical-chunking]
verify_jwt = true
