
project_id = "bfscrjrjwbzpldamcrbz"

[functions.gemini-chat]
verify_jwt = false

[functions.analytics-insights]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
