
name: Deploy Firebase Functions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write        # OIDC for Workload Identity

    steps:
    - uses: actions/checkout@v4

    # Authenticate to Google Cloud as default CF service‑account
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/770738639376/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'dws-ai@dws-ai-1000.iam.gserviceaccount.com'

    - run: npm install -g firebase-tools

    # Install deps & build functions
    - run: npm ci
      working-directory: ./functions

    # Deploy functions + Firestore indexes
    - run: firebase deploy --only functions,firestore:indexes --project dws-ai-1000

