
name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Root Dependencies
        run: npm ci || npm install
        
      - name: Install Functions Dependencies
        run: npm ci || npm install
        working-directory: ./functions
        
      - name: Build Application
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase
        run: firebase deploy --only functions,firestore:indexes,hosting --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
